### ISSUE TITLE
Backend-Pipeline erstellen

### ISSUE THREAD

**Issue by sansyan-q** [ZDDduesseldorf/HandScanAI#34]
(Stand: Done, dient ggf. als Nachschlagewerk)

## Grober Aufbau Pipeline
(Siehe Diagramme unten für ausführlichere Informationen.)
- 11K Datenbank filtern (validation)
- hand normalisation
- embeddings
- (wenn es implementiert ist an Vectordatenbank weitergeben und Abstände prüfen, #35, #44)

## Informationen
Dokumentation in 
- Readmes
- Miro (https://miro.com/app/board/uXjVL9vUUw4=/) 
- Figma (https://www.figma.com/design/wc5S8DMRBfblrsDEkINNh4/HandScanAI?node-id=30-2&node-type=canvas&t=3MbLn3sgjwoFSKP0-0)

## TODOs

- [x] **11k datenset filtern**: code aufbauen und datensatz erstellen (sander)
- [x] **datasets erstellen** (sander)
- [x] **hand normalisation**: nach backend umziehen (sander o. lukas)
- [x] **hand normalisation**: in die initial_data_pipeline einfügen (lea + marina)
- [x] **embeddings**: input für Methoden anpassen, um dataset-Listen entgegenzunehmen (marina)
- [x] **embeddings**: korrekte Reihenfolge der Embeddings-Ausgabe sicherstellen, Dataset anpassen (marina) --> Die Einhaltung der richtigen Reihenfolge ist die Aufgabe des datasets, die embeddings selbst kriegen nur eine Liste an Bildern und geben die zugehörigen Embeddings in derselben Reihenfolge raus
- [x] **pipeline**: einfügen der embeddings (marina) (wartet auf hand normalization)
- [x] **pipeline**: pipeline-Teile in Unterordner verschieben (marina)
- [x] **pipeline**: pipeline selbst in Unterordner verschieben/ von backend aus aufrufbar machen/ Pfade anpassen, um es von Unterordner aus aufrufbar zu machen
- [x] **pipeline**: übrige pipelines anlegen (s.u., lea)
- [ ] Potenziell Zusätzliche Funktion für Wrapping von Embeddings in äußeres Dict, Refactoring der EMbeddings und aussortieren nicht benutzter Funktionen --> wurde dokumentiert, in neues Issue auslagern und ggf. mit update der docstrings verbinden
- [ ] **pipeline**: Dokumentation (e.g. Readme, lea + marina) --> Dokumentation der Pipelines in Figma und Miro, Anpassung der Dokumentation nach Hinzufügen der Databases und Update der Readme in Folge-Issue
- [ ] tests für validation und filter (?) --> in anderes Issue auslagern
- [x] tests für hand normalisation (?)
- [x] tests für embeddings (marina)
- [x] tests für pipelines

## Entscheidungen
- _pipeline: werden embeddings einmal durchlaufen und zwischengespeichert oder wird pro UUID einmal von Embeddings zur Einspeicherung in Trees durchlaufen?_ 
  - --> Zweiteres: Embeddings werden errechnet und direkt an die Vectordatenbank weitergegeben, ohne sie zwischendurch nochmal abzulegen
- _wie passen wir die initial_data_pipeline an und rufen sie auf, damit die Input-Pfade funktionieren_ 
  - --> atm in manage.py. Die anderen beiden Pipelines müssten von API aus getriggert werden, TODO Implementierung
- Aufbau zusätzlicher Pipelines 
  - [x] initial_data_pipeline zum Beladen durch vorhandenes Datenset (erste Pipeline, die implementiert wird)
  - [x] classifier_pipeline (umbenannt) zum Klassifizieren eines input-Bildes (Skizze Miro und Figma)
  - [x] save_new_datapoint_pipeline (umbenannt) zum Abspeichern eines einzelnen Bildes mitsamt der Metadaten (Skizze Miro und Figma)
- _embeddings: arbeiten wir weiterhin mit Listen (ab dem Dataset), oder geben wir aus dem Dataset stattdessen ein dict mit den Region names raus und reichen es durch die embeddings-Funktionen weiter? Eventuell wird dadurch das Error Handling einfacher_ 
  - --> Entscheidung für Dicts, Verwendung, Aufbau und Keys siehe Miro, Beispiel: 
<img width="813" alt="image" src="https://github.com/user-attachments/assets/a168e0f8-8a04-4257-8b44-b0c198393446" />

## Zu klären (Struktur Backend/ Utils) --> Tessa --> Konzept, Umsetzung in neuem Issue
Module/ Methoden, die wir für mehrere Module brauchen und deren Platzierung wir evtl überarbeiten (oder mit den anderen besprechen) müssen:

- [ ] app/utils/uuid.py (könnte evtl. aus der app raus in backend gezogen werden)
- [ ] load image 
  - bspw in embeddings/image_utils.py: wird das für irgendwas anderes außer die embeddings benutzt? 
  - Wir haben grade verschiedene Methoden, Pfade zu bauen in image_utils, den test-configs und der pipeline. 
  - Man könnte schauen, wo es das alles gibt, was man für welchen Zweck braucht und ob man das in allgemeinen image_utils vereinheitlichen kann.
- [ ] Regions für Bilder-Pfade/ korrekte Zuordnung der Bilder zu Embeddings, Suchbäumen, später evtl. Classifiern
- [ ] extract from filenames in Datasets (marked by TODO)

## Aufgaben für andere Issues
- Implementierung von Vectordatenbank und Integration in die Pipelines (Issues s.o.)
- automatische Synchronisierung des BaseDatasets/ der Image Folder mit bspw. Teams (momentan findet das Auslesen und die Bilder-Ablage in lokalen Ordnern statt, die man sich selbst anlegen/ ggf. befüllen muss) --> hat sich wahrscheinlich durch das Einfügen von Datenbanken erledigt
- Speicherung der Bilder + Metadaten in Datenbank --> siehe db-Ticket #43 , Anpassung der Pipeline in Folge-Issue und nicht im Rahmen dieses Issues
- Error Handling beim Einlesen von Bildern mit opencv (falscher Pfad) --> TODO: Ticket Errorhandling, wird ggf. im Zuge des Refactoring für den Linter oder in den Tests schon behoben (#30 )

## Potenziell Anzulegende Issues (ergibt sich aus obigen Beschreibungen)
- Anpassung README: Python Backend muss 3.10.x (am besten 3.10.7) sein. Ab 3.11 funktioniert es nicht mehr
- Refactoring Embeddings (siehe unter TODOs)
- Anpassung der pipelines und der Dokumentation und README (siehe unter TODOs, relevant bei Integration der Vectordatenbanken/ Datenbanken)
- Tests für Validation und Filter (ggf. in Kombi mit #28 )
- Anbindung Pipelines an API/ Trigger durch Frontend
- Neustruktierung Utils (Absprache Tessa, s.o.)
- Neustrukturierung Pipeline-Ordner (evtl in Kombi mit anderem Ticket)
- Errorhandling beim Einlesen von Bildern mit opencv in Hand-Normalization (siehe Aufgaben für andere Issues, evtl nach Einbindung der Datenbanken irrelevant)
- Entscheidungsfindung/ Klassifizierung des Bildes: erstmal RandomForest?
- Filtern des 11K Datensatzes anpassen (bspw. mehrfach dieselbe ID rauswerfen, testen ob die Änderung der default-Werte in #48 einen Unterschied machen und angepasst werden müssen)
