### ISSUE TITLE
Dokumentation planen/ strukturieren

### ISSUE THREAD

**Issue by confusima** [ZDDduesseldorf/HandScanAI#47]
Ziel ist es, eine vollständige Übersicht der enthaltenen Methoden und Dateien zu erstellen, die Dokumentationsabdeckung zu prüfen und eine Konzeption zur Restrukturierung zu entwickeln. Zusätzlich soll die Sphinx-Dokumentation zur automatischen Generierung der Doku integriert werden.

**To-Do:**

- [ ] Methoden- und File-Overview Draft: https://miro.com/app/board/uXjVL9vUUw4=/

- [ ] Dokumentationsabdeckung: Überprüfen, wo noch Doku fehlt, und fehlende Teile ergänzen. DocString Konvention.

- [ ] Sphinx-Doku-Generation: Integration von Sphinx zur automatischen Generierung der Dokumentation: https://www.sphinx-doc.org/en/master/index.html

**Comment by sansyan-q** [comment]
Übersicht zu Dokumentationsabdeckung siehe #85

**Comment by sansyan-q** [comment]
@confusima Docstring-Konvention müsste den Teammitgliedern mitgeteilt werden, weil die Dokumentationsarbeit jetzt langsam anfangen soll. Gibt es da schon eine konkrete Vorgabe?

**Comment by confusima** [comment]
Ich würde diese VSCode Extension empfehlen, muss dann nur noch stellenweise um z.B. Methodenzweck ergänzt werden: https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring

**Comment by sansyan-q** [comment]
wird misused für Doku-Planung backend-Team

# Übersicht 1 der Dokumentation TODO-Liste

## backend 

(nicht zwingend wir)
- README (übersetzen)
- Ordner-Struktur und Beschreibungen updaten
- evtl. umstrukturieren (erst Projektstruktur, dann Information für Development?)

## app 

(nicht zwingend wir)
--> in backend-README dokumentiert
- evtl kann man hier entweder noch eine eigene README hinzufügen oder genauere Informationen zur backend-README hinzufügen über
-- graphql, rest, websocket (kurze Info, was wofür verwendet wird/ wofür wichtig ist)
-- Schnittstelle API zu Pipelines (wo ist der Einstiegspunkt von Frontend, von wo werden die Pipelines aufgerufen)

## classifier 

(Lea)
- README
- docstrings

## embeddings 

(Marina)
- evtl in README hinzufügen, dass in embeddings-utils die embeddings auch normalized werden
- Currently implemented besser formulieren
- Tabelle in embeddings-README hinzufügen über die implementierten Modelle, in die wir die Testwerte eingeben können
- evtl currently implemented und entry Points in README tauschen
- evtl bessere Erklärung hinzufügen, was in dem Embeddings-Modul wirklich passiert? (siehe hand-normalization)
- sind die docstrings soweit alle ok?

## hand-normalization 

(nicht zwingend wir, nicht weiter beachtet)
- TODO
- TestImages aus hand-normalization löschen

- evtl. Hinweise hinzufügen, worauf man achten muss, um Bilder zu machen, die durch die normalization kommen (z.B. gleichmäßiges lighting, keine starken Schatten, keine anderen Sachen im Hintergrund/ am Rand, am besten weißer Hintergrund etc.)

## pipelines 
- Diagramm- und README update siehe Issue
- docstrings von initial data Pipeline und add new embeddings Pipeline wurden geupdated in Pipeline refactoring,der rest muss nochmal geprüft werden

## Tests
- updates siehe Issue (bereits übersetzt, szenarios noch nicht erklärt)
- müssen noch Sachen refactored oder geaddet werden (bspw. pipeline-Tests?)
- integrationstest mit hand-normalization ist noch nicht implementiert (TODO in anderem Ticket)

## utils
- die sind glaube ich fertig? muss da noch was an den docstrings gemacht werden?
- bei image-utils ist noch ein TODO wegen docstrings drin, die logging-utils wurden in dem pipeline-refactoring-branch mit docstrings versehen

## Validation
- keine Ahnung, hat keine README. Steht da was in der backend-README dazu?

## vectordb
- idk, ich glaub die README war soweit ok? müssen wir da noch die docstrings anpassen von 'nderungen von uns?

## manage.py
- update docstrings von filter11k und Setup csv logging

**Comment by sansyan-q** [comment]
@s6l6m , @SanderTeb , @lukeweide 
Wir haben hier im vorherigen Kommentar eine grobe Übersicht über die noch ausstehenden Doku-Sachen gemacht fürs backend, das ist vllt als Übersicht für euch auch nützlich. wenn ihr da was ergänzen wollt, hängt euch gerne dran. für einzelne Sachen gibt es auch schon extra Issues

**Comment by sansyan-q** [comment]
schließen, wird im #85
