### ISSUE TITLE
Embeddings Testszenarien planen und umsetzen

### ISSUE THREAD

**Issue by sansyan-q** [ZDDduesseldorf/HandScanAI#64]
siehe #62 
Erster merge der Embeddings-Teststruktur siehe #83 
Zweiter Merge mit Fehlerbehebung siehe #97 

Durchführung der Tests und Auswertung ausstehend (s.u. TODOs)

## Konkrete Ergebnisse
Allgemein:
- Vorerst Nutzung der Cosinus-Distanzberechnung
- nächste Nachbarn mind. 5 (aber gleichbleibender Wert für alle Tests eines Durchgangs)
- Hier wird der Fokus erst mal nur aufs Modell gelegt
- Ergebnisse mitspeichern (bspw. in CSV-Datei, Text-Datei, Hand-Normalisierungs-Bilder (zum Vergleichen) in eigenen Ordnern)
  - Auch Ergebnisse der Distanzberechnung mitspeichern: csv speichern unter uuid_{timestamp/beschreibung testcase}_embeddings_test.csv (query-datenpunkt informationen und dictionary der nächsten nachbarn: distanzen, metadaten) -> einfacher zum Vergleichen
  - **Besprechung**: gibt es für sowas sinnvolle Logging/ Auswertungs-Tools? Falls ja, die benutzen
- Versuchsaufbau so dokumentieren und einrichten, dass er für andere Distanzberechnungen wiederholt werden kann
- Bias- und Lücken-Überprüfung der Testdaten/ BaseDataset (da gefiltert und nicht mehr übereinstimmend mit 11K)
  - Altersverteilung
  - Gender
  - Hautfarbe (auch nach Alter und Gender verteilt)
  - Accessories (auch nach Alter und Gender verteilt)
  - left-right-Verteilung (auch nach Alter und Gender verteilt)

Für alle Modelle die Embeddings-Daten errechnen und abspeichern (erleichtert den Vergleich)
- entweder über CSV-Daten (preferierte Methode, da relativ wenig Aufwand)
- oder in versch. Collections in der Vectordatenbank (erst relevant, wenn das implementiert ist, evtl. zu aufwendig)

Tests:
- Wie unterscheiden sich die Ergebnisse der Distanzberechnung zwischen den Embeddings der Modelle?
  - Gibt es Tools, mit denen wir den Vergleich automatisiert machen können?
  - Manueller Vergleich: 
    - Eingabebild vergleichen mit den k niedrigsten Distanzen

Szenarien: 
- Bild aus dem Testdatensatz als Testbild nehmen (11K)
  - Vergleichen dieses Testbildes mit den anderen Bildern derselben Person aus dem Datensatz
    - Dieselbe Hand
    - Rechte Hand mit linker Hand
    - These: Bilder derselben Person sollten trotz unterschiedlicher Handposition oder Seite die ähnlichsten Embeddings im Vergleich zu anderen Personen liefern
- Augmentation: Teil vom Testdatensatz raussuchen (ebenfalls wieder Bilder derselben Person und einiger zusätzlicher)
  - In der hand-normalization randomisierte Data Augmentation einfügen und dadurch den ausgesuchten Test-Datensatz vergrößern (so bekommen wir ähnliche Bilder derselben Personen leicht abgeändert)
  - augmented Bilder werden abgespeichert, genau wie die Werte, mit denen sie augmentiert wurden (für Auswertung)
  - Vergleichen der Distanzen und der zugehörigen Bilder: 
    - Die ähnlichsten Bilder sollten von derselben Person sein. 
    - Wie wirken sich verschiedene Augmentations (Kontrast/ Helligkeit, Crop, Rotation) auf die Ähnlichkeitsmessung aus?
- Mit unseren Bildern die beiden selben Testaufbauten wie oben für die Testdatensatz-Bilder aufbauen und vergleichen, ob sich die Distanzwerte und die ähnlichsten Bilder im selben Rahmen befinden oder sich stark unterscheiden

"Gute Ergebnisse" dieser Tests sind: Bilder derselben Person erzielen die ähnlichsten Distanzwerte im Vergleich zu Bildern anderer Personen

Tests, ob die Distanzen zu anderen Personen gut funktionieren, werden im Klassifizierungs-Test gemacht, weil dort die Metadaten für die Klassifizierung mit in Betracht gezogen werden müssen

---
## Besprechung
Bias-Verteilung für Besprechung, siehe [Kommentar](https://github.com/ZDDduesseldorf/HandScanAI/issues/64#issuecomment-2579570824)

---

## TODO:
- [x] Normalisierung der Embeddings mit einfügen
- [x] Normalisierung und Milvus in Testdurchläuft integrieren
- [x] Timing und Logging der Embeddings-Berechnung (zum Vergleich der Modelle)
- [x] Szenario 1
  - [x] 2-3 Bilder aus dem Testdatensatz als Testbilder nehmen, mit uuids hinterlegen (momentan sind wahllose uuids drin)
    - Bilder müssen von derselben Person ein Bild der anderen Hand im Datensatz haben (gewählte Bilder und zugehörige dokumentieren)
  - [x] Auswertung des Tests
- (ausgelagert) #94
  - Augmentation-Step implementieren (Augmentation in hand_normalization, Speichern der Bilder, Logging der Augmentiation s.o.)
  - 2-3 Bilder aus dem Testdatensatz nehmen für Augmentation
  - Auswertung (e.g. Wie wirken sich verschiedene Augmentations (Kontrast/ Helligkeit, Crop, Rotation) auf die Ähnlichkeitsmessung aus?)
- (ausgelagert) #117 
  - Unsere eigenen Bilder für die steps der beiden vorherigen Szenarien verwenden 
--> das wird ein informeller Test, bei dem wir schauen, ob die Bilder derselben Person genommen werden, wird aber keine Auswertung wie unten geben

Info:
- Wir hatten bisher für die Tests NUR das 11K verwendet, das als Base-Datenset in Teams ist (BaseDataset11K, 11.Februar)
- Wenn wir das Datenset mit unseren Daten zusätzlich benutzen, müssten wir alle Modi nochmal durchgehen

### Timer:

|Anzahl Bilder|model|Dauer Embeddings-Berechnung|
|-|-|-|
|4|DENSENET_121|2372.07|
|4|DENSENET_169|3057.80|
|4|RESNET_50|2159.97|

|Anzahl Bilder|model|Dauer Embeddings-Berechnung|
|-|-|-|
|269|DENSENET_121|149642.35|
|269|DENSENET_169|204092.54|
|269|RESNET_50|141716.08|

#### CSV und Cosinus-Distanz aus scipy
![Image](https://github.com/user-attachments/assets/86f8c688-19d5-4344-9e94-ffdfd5774212)

#### Milvus und Cosinus-Ähnlichkeit

Einstellungen Milvus: 
- milvus-metric-type: cosine
- index-type: Flat
- nlist: 128
- nprobe: 10

![Image](https://github.com/user-attachments/assets/39128ec0-400a-4f74-bdcf-b4e36e195abf)

### Similarity-Auswertung für gleiches Bild

Erwartung: Similarity = 1

![Image](https://github.com/user-attachments/assets/45c80268-e229-4c38-af58-5f2490bc58e3)

### Zusätzliche Erkenntnisse
- Accessoires (hier: Ring) machen einen substanziellen Unterschied, ob die Hand derselben Person gefunden wird (schlechte Ergebnisse beim Finden von Händen ohne Ring derselben Hand (geht), der anderen Hand (sehr schlecht)). Beispiel (siehe auch Auswertungstabellen Teams):
  - cb151d9a-f267-44fd-b8ad-e35a7ec6e43e mit Ring
  - 5fb19ec5-65d0-43ae-9460-8dac1040dbf1 ohne Ring

## Entscheidung, welches Modell Default ist
Auf obenstehenden Daten:
- **Entscheidung**: **DenseNet_121** als Default behalten
- **Begründung**: Kompromiss zwischen Schnelligkeit und Trefferquote. ResNet-50 ist zwar das schnellste und größte Modell, hat aber vergleichsweise die schlechteste Trefferquote. DenseNet_169 ist das langsamste Modell mit den größten Embeddings (braucht daher auch mehr Arbeitsspeicher und Speicher), unterscheidet sich von der Genauigkeit aber so wenig vom DenseNet_121, dass sich der Austausch momentan nicht lohnt. Wenn mehr eigene Daten erhoben wurden, sollten die Tests wiederholt werden, weil sich dadurch ggf. die Ergebnisse nochmal ändern können.

**Comment by leamueller06** [comment]
Timer:

Dauer Initial:2159.9671840667725
model:C:\Users\leamu\Documents\1_uni\Medieninformatik\HandScanAI\git\HandScanAI\backend\tests\scenario_embeddings\result_csvs\RESNET_50
Dauer Initial:3057.7950477600098
model:C:\Users\leamu\Documents\1_uni\Medieninformatik\HandScanAI\git\HandScanAI\backend\tests\scenario_embeddings\result_csvs\DENSENET_169
Dauer Initial:2372.0667362213135
model:C:\Users\leamu\Documents\1_uni\Medieninformatik\HandScanAI\git\HandScanAI\backend\tests\scenario_embeddings\result_csvs\DENSENET_121

**Comment by leamueller06** [comment]
mögliche Testbilder

gender | old_id| uuid | left/right | age
---|---|---|---|---|
female | 1592| 946e0eb9-5b0a-4e56-b99a-e665ac40de89| right | 20
|| |4179975e-fca3-4beb-a2c9-10cc700ed5f4 | left||
female | 1510 | 516d1d19-61c4-42e9-b2dc-2697e0ecb743| left | 23
|||ae08cae5-e439-41b0-a04b-6783ef08363f|left||
|||dc10940a-69d0-4f6a-b755-44b3203be5eb|left||
|||6976a5cd-276a-46d9-9e36-346c9bc0782a|right||
|||a8a6ccb8-35dc-4108-86c8-0dbbee6923b0|right||
|||ba3cc7cc-0300-42e3-8325-a23f5dc2b46e|right||
female | 86 | 218ce52f-4a15-42d9-8e1e-2d40492fc1ce| left | 21
|||37fd0c56-a371-4399-89af-02a06bfb3794| left ||
|||e9ca6519-1380-4941-8850-a88605fca7ab|left||
|||23698a1f-d9ce-4df1-bd3a-e1de61a8f727|right||
|||54537423-bf5a-4c6e-9c79-f78f036728bd|right||
male | 1536 | 483d35a9-c222-4509-ad8c-e3ebecf758d| right | 22
||| f4888357-c449-45eb-978a-a53312a5314f | left ||

**Comment by leamueller06** [comment]
{'Hand':                                    uuid  distance age gender
0  514f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  614f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  514f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  714f53d0-6aab-4da1-b929-8f1dc0817289  0.072320  20      0
0  814f53d0-6aab-4da1-b929-8f1dc0817289  0.112967  20      0, 'HandBody':                                    uuid  distance age gender
0  514f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  614f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  514f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  0d16db56-1260-4d4d-8d74-3b42b82dc4ab  0.162228  23      1
0  714f53d0-6aab-4da1-b929-8f1dc0817289  0.178043  20      0, 'Thumb':                                    uuid  distance age gender
0  514f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  614f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  514f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  714f53d0-6aab-4da1-b929-8f1dc0817289  0.123542  20      0
0  814f53d0-6aab-4da1-b929-8f1dc0817289  0.165797  20      0, 'IndexFinger':                                    uuid  distance age gender
0  514f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  614f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  514f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  714f53d0-6aab-4da1-b929-8f1dc0817289  0.155582  20      0
0  0d16db56-1260-4d4d-8d74-3b42b82dc4ab  0.187639  23      1, 'MiddleFinger':                                    uuid  distance age gender
0  514f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  614f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  514f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  714f53d0-6aab-4da1-b929-8f1dc0817289  0.115203  20      0
0  814f53d0-6aab-4da1-b929-8f1dc0817289  0.177315  20      0, 'RingFinger':                                    uuid  distance age gender
0  514f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  614f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  514f53d0-6aab-4da1-b929-8f1dc0817289  0.000000  27      1
0  814f53d0-6aab-4da1-b929-8f1dc0817289  0.152786  20      0
0  714f53d0-6aab-4da1-b929-8f1dc0817289  0.163198  20      0, 'LittleFinger':                                    uuid      distance age gender
0  514f53d0-6aab-4da1-b929-8f1dc0817289  2.220446e-16  27      1
0  614f53d0-6aab-4da1-b929-8f1dc0817289  2.220446e-16  27      1
0  514f53d0-6aab-4da1-b929-8f1dc0817289  2.220446e-16  27      1
0  714f53d0-6aab-4da1-b929-8f1dc0817289  1.378880e-01  20      0
0  814f53d0-6aab-4da1-b929-8f1dc0817289  1.581665e-01  20      0}


extrem kleine Distanzen von e-16 kommen wahrscheinlich aus Rundungsfehlern aus Distanzberechnung, da Embeddings nach Überpürfung exakt identisch sind. 
TODO: Muss nochmal überprüft werden Wenn Milvus eingefügt wurde

**Comment by sansyan-q** [comment]
<img width="551" alt="Image" src="https://github.com/user-attachments/assets/e1f4a2d7-792f-4eda-b7b2-405868746366" />
Erste Auswertung

TODO:
- Entscheiden, welches Modell wir nehmen (auf Grundlage Schnelligkeit und Performance)
- Bias links/rechts auswerten (niedrige Prio, Nice to Have)
